[template.environment]
  GQL_HOST = "WordPress URL https://cms.tail.dk/graphql"
  NUXT_IMAGE_DOMAINS = "Comma separated list of domains. tail.dk"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.cms.tail.dk/.*"]
